default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: krisllayne
  password: "@98971526@"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_noticias_development

test:
  <<: *default
  database: app_noticias_test

production:
  <<: *default
  database: app_noticias_production
  username: app_noticias
  password: <%= ENV['APP_NOTICIAS_DATABASE_PASSWORD'] %>
