default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: "@98971526@"
  pool: 5

development:
  <<: *default
  database: app_noticias_development

test:
  <<: *default
  database: app_noticias_test

production:
  <<: *default
  database: app_noticias_production
